version: '3.8'

networks:
  simple-django-network:

volumes:
  simple-django-volume:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DB}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8001:8001"
    networks:
      - simple-django-network
    volumes:
      - simple-django-volume:/app
    env_file:
      - .env.web

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - simple-django-network
    volumes:
      - simple-django-volume:/var/lib/mysql
    env_file:
      - .env.db

